### ISSUE TITLE
Password resets

### ISSUE THREAD

**Issue by agathver** [librecores/librecores-web#192]
We would like to have proper password reset emails. We use [FOSUserBundle which provides logic and starter templates](http://symfony.com/doc/master/bundles/FOSUserBundle/emails.html) for password reset.

However, the UI needs to match the design of LibreCores.org

**Comment by eliaskousk** [comment]
I have been assigned the relevant FOS user bundle improvements
(registrations, lost password etc) a couple of months or more ago but
unfortunately I still haven't found time to complete them. I'll try harder
to find the time so give me until next month and if I don't deliver by all
means let's assign this to someone else!

**Comment by wallento** [comment]
Hi @eliaskousk,

the idea is to have a few simpler sub-tasks for hacktoberfest. Do you think this is not separable from your work?

Cheers,
Stefan

**Comment by eliaskousk** [comment]
This should be simple enough to get down over this weekend. I'll take a
look and let you know.

**Comment by agathver** [comment]
Hi @eliaskousk 
>I have been assigned the relevant FOS user bundle improvements (registrations, lost password etc) a couple of months or more ago but unfortunately I still haven't found time to complete them

Oh! I wasn't aware of that.

The aim here is to put up simple tasks so that we can get new contributors. Since we know the way around the source code, we should concentrate on more complex tasks.

**Comment by eliaskousk** [comment]
Hi @agathver,

since you recent very good work I think I belong to this category haha :)
Seriously though I'll take a look at it and see if I can handle it or not (due to me being terrible on frontend work).

**Comment by scarecrow21** [comment]
Hi. I'm a newbie here. Will someone guide me through solving this?

**Comment by sandipbhuyan** [comment]
Is it ope?. I want to work on this.

**Comment by agathver** [comment]
// cc @eliaskousk

**Comment by imphil** [comment]
@sandipbhuyan this is mostly resolved in PR https://github.com/librecores/librecores-web/pull/193. However, in order to merge this we first need a verified e-mail address from the user. Would that be something for you to work on? There is more discussion on that in https://github.com/librecores/librecores-web/issues/142

**Comment by eliaskousk** [comment]
@imphil Is the plan for the AWS e-mail service still on? Let me know if I can somehow help with this. I'll take a look at the other issues as well and see if there is anything urgent.

**Comment by imphil** [comment]
@eliaskousk yes, the plan is to use AWS email for such transactional mail. Probably the most simple route is simply setting up swiftmail using their SMTP servers

**Comment by sandipbhuyan** [comment]
I have raised a PR for email verification process. For reseting the password FOSUserBundler have some predefined  functionality. We can modify the UI also  by overriding the default pages. @imphil   I am looking forward to resolve this Issue.

**Comment by juliusbaxter** [comment]
Hi all, any progress on this? It seems to me the facility is still missing from the site.

**Comment by agathver** [comment]
Fixed in #193
